// <auto-generated />
using System;
using APBD_Proj.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBD_Proj.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBD_Proj.Models.Companies", b =>
                {
                    b.Property<int>("IdCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompany"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<long>("KRS")
                        .HasMaxLength(14)
                        .HasColumnType("bigint")
                        .HasColumnName("KRS");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("IdCompany");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            IdCompany = 1,
                            Address = "123 Tech Street",
                            Email = "contact@techcorp.com",
                            KRS = 12345678901234L,
                            Name = "TechCorp",
                            PhoneNumber = 555123456
                        },
                        new
                        {
                            IdCompany = 2,
                            Address = "456 Biz Avenue",
                            Email = "info@bizcorp.com",
                            KRS = 43210987654321L,
                            Name = "BizCorp",
                            PhoneNumber = 555654321
                        });
                });

            modelBuilder.Entity("APBD_Proj.Models.Contracts", b =>
                {
                    b.Property<int>("IdContract")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ContractID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContract"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<int?>("IdCompany")
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    b.Property<int?>("IdCustomer")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<int?>("IdDiscount")
                        .HasColumnType("int")
                        .HasColumnName("DiscountID");

                    b.Property<int>("IdSoftware")
                        .HasColumnType("int")
                        .HasColumnName("SoftwareID");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit")
                        .HasColumnName("IsPaid");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit")
                        .HasColumnName("IsSigned");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalAmount");

                    b.Property<int>("YearsOfSupport")
                        .HasColumnType("int")
                        .HasColumnName("YearsOfSupport");

                    b.HasKey("IdContract");

                    b.HasIndex("IdCompany");

                    b.HasIndex("IdCustomer");

                    b.HasIndex("IdDiscount");

                    b.HasIndex("IdSoftware");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            IdContract = 1,
                            EndDate = new DateTime(2025, 6, 27, 21, 10, 22, 55, DateTimeKind.Local).AddTicks(2049),
                            IdCompany = 1,
                            IdCustomer = 1,
                            IdDiscount = 1,
                            IdSoftware = 1,
                            IsPaid = true,
                            IsSigned = true,
                            StartDate = new DateTime(2024, 6, 27, 21, 10, 22, 55, DateTimeKind.Local).AddTicks(1850),
                            TotalAmount = 1000.0m,
                            YearsOfSupport = 1
                        },
                        new
                        {
                            IdContract = 2,
                            EndDate = new DateTime(2025, 6, 27, 21, 10, 22, 55, DateTimeKind.Local).AddTicks(3155),
                            IdCompany = 2,
                            IdCustomer = 2,
                            IdDiscount = 2,
                            IdSoftware = 2,
                            IsPaid = false,
                            IsSigned = false,
                            StartDate = new DateTime(2024, 6, 27, 21, 10, 22, 55, DateTimeKind.Local).AddTicks(3146),
                            TotalAmount = 2000.0m,
                            YearsOfSupport = 2
                        });
                });

            modelBuilder.Entity("APBD_Proj.Models.Customers", b =>
                {
                    b.Property<int>("IdCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCustomer"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("LastName");

                    b.Property<long>("Pesel")
                        .HasMaxLength(11)
                        .HasColumnType("bigint")
                        .HasColumnName("Pesel");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("IdCustomer");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            IdCustomer = 1,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Doe",
                            Pesel = 12345678901L,
                            PhoneNumber = 123456789
                        },
                        new
                        {
                            IdCustomer = 2,
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            IsDeleted = false,
                            LastName = "Smith",
                            Pesel = 98765432101L,
                            PhoneNumber = 987654321
                        });
                });

            modelBuilder.Entity("APBD_Proj.Models.Discounts", b =>
                {
                    b.Property<int>("IdDiscount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DiscountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiscount"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Percentage");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.HasKey("IdDiscount");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            IdDiscount = 1,
                            EndDate = new DateTime(2024, 7, 17, 21, 10, 22, 54, DateTimeKind.Local).AddTicks(8795),
                            Name = "Summer Sale",
                            Percentage = 10.0m,
                            StartDate = new DateTime(2024, 6, 17, 21, 10, 22, 52, DateTimeKind.Local).AddTicks(4970)
                        },
                        new
                        {
                            IdDiscount = 2,
                            EndDate = new DateTime(2024, 6, 17, 21, 10, 22, 54, DateTimeKind.Local).AddTicks(9103),
                            Name = "Winter Sale",
                            Percentage = 20.0m,
                            StartDate = new DateTime(2024, 5, 28, 21, 10, 22, 54, DateTimeKind.Local).AddTicks(9093)
                        });
                });

            modelBuilder.Entity("APBD_Proj.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "hashedpassword",
                            Role = "Administrator",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "hashedpassword",
                            Role = "User",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("APBD_Proj.Models.Payments", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<string>("ClientInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClientInfo");

                    b.Property<int>("IdContract")
                        .HasColumnType("int")
                        .HasColumnName("ContractID");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PaymentDate");

                    b.HasKey("PaymentId");

                    b.HasIndex("IdContract");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 500.0m,
                            ClientInfo = "John Doe",
                            IdContract = 1,
                            PaymentDate = new DateTime(2024, 6, 27, 21, 10, 22, 55, DateTimeKind.Local).AddTicks(4258)
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 1000.0m,
                            ClientInfo = "Jane Smith",
                            IdContract = 2,
                            PaymentDate = new DateTime(2024, 6, 27, 21, 10, 22, 55, DateTimeKind.Local).AddTicks(4752)
                        });
                });

            modelBuilder.Entity("APBD_Proj.Models.Software", b =>
                {
                    b.Property<int>("IdSoftware")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SoftwareID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSoftware"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Version");

                    b.HasKey("IdSoftware");

                    b.ToTable("Softwares");

                    b.HasData(
                        new
                        {
                            IdSoftware = 1,
                            Category = "Utility",
                            Description = "A super application",
                            Name = "SuperApp",
                            Version = "1.0"
                        },
                        new
                        {
                            IdSoftware = 2,
                            Category = "Business",
                            Description = "A mega application",
                            Name = "MegaApp",
                            Version = "2.0"
                        });
                });

            modelBuilder.Entity("APBD_Proj.Models.Subscriptions", b =>
                {
                    b.Property<int>("IdSubscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubscriptionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubscription"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<int?>("IdCompany")
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    b.Property<int?>("IdCustomer")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<int>("IdSoftware")
                        .HasColumnType("int")
                        .HasColumnName("SoftwareID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<int>("RenewalPeriod")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("RenewalPeriod");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.HasKey("IdSubscription");

                    b.HasIndex("IdCompany");

                    b.HasIndex("IdCustomer");

                    b.HasIndex("IdSoftware");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            IdSubscription = 1,
                            EndDate = new DateTime(2025, 6, 27, 21, 10, 22, 55, DateTimeKind.Local).AddTicks(6316),
                            IdCompany = 1,
                            IdCustomer = 1,
                            IdSoftware = 1,
                            IsActive = true,
                            Price = 100.0m,
                            RenewalPeriod = 12,
                            StartDate = new DateTime(2024, 6, 27, 21, 10, 22, 55, DateTimeKind.Local).AddTicks(6127)
                        },
                        new
                        {
                            IdSubscription = 2,
                            EndDate = new DateTime(2026, 6, 27, 21, 10, 22, 55, DateTimeKind.Local).AddTicks(6880),
                            IdCompany = 2,
                            IdCustomer = 2,
                            IdSoftware = 2,
                            IsActive = false,
                            Price = 200.0m,
                            RenewalPeriod = 24,
                            StartDate = new DateTime(2024, 6, 27, 21, 10, 22, 55, DateTimeKind.Local).AddTicks(6871)
                        });
                });

            modelBuilder.Entity("APBD_Proj.Models.SubscriptionsPayments", b =>
                {
                    b.Property<int>("IdPayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPayment"));

                    b.Property<decimal>("Ammount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdSubscription")
                        .HasColumnType("int");

                    b.HasKey("IdPayment");

                    b.HasIndex("IdSubscription");

                    b.ToTable("SubscriptionsPayments");

                    b.HasData(
                        new
                        {
                            IdPayment = 1,
                            Ammount = 100.0m,
                            IdSubscription = 1
                        },
                        new
                        {
                            IdPayment = 2,
                            Ammount = 200.0m,
                            IdSubscription = 2
                        });
                });

            modelBuilder.Entity("APBD_Proj.Models.Contracts", b =>
                {
                    b.HasOne("APBD_Proj.Models.Companies", "Companies")
                        .WithMany("Contracts")
                        .HasForeignKey("IdCompany");

                    b.HasOne("APBD_Proj.Models.Customers", "Customers")
                        .WithMany("Contracts")
                        .HasForeignKey("IdCustomer");

                    b.HasOne("APBD_Proj.Models.Discounts", "Discounts")
                        .WithMany("Contracts")
                        .HasForeignKey("IdDiscount");

                    b.HasOne("APBD_Proj.Models.Software", "Software")
                        .WithMany("Contracts")
                        .HasForeignKey("IdSoftware")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Companies");

                    b.Navigation("Customers");

                    b.Navigation("Discounts");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("APBD_Proj.Models.Payments", b =>
                {
                    b.HasOne("APBD_Proj.Models.Contracts", "Contracts")
                        .WithMany("Payments")
                        .HasForeignKey("IdContract")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("APBD_Proj.Models.Subscriptions", b =>
                {
                    b.HasOne("APBD_Proj.Models.Companies", "Companies")
                        .WithMany("Subscriptions")
                        .HasForeignKey("IdCompany");

                    b.HasOne("APBD_Proj.Models.Customers", "Customers")
                        .WithMany("Subscriptions")
                        .HasForeignKey("IdCustomer");

                    b.HasOne("APBD_Proj.Models.Software", "Software")
                        .WithMany("Subscriptions")
                        .HasForeignKey("IdSoftware")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Companies");

                    b.Navigation("Customers");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("APBD_Proj.Models.SubscriptionsPayments", b =>
                {
                    b.HasOne("APBD_Proj.Models.Subscriptions", "Subscriptions")
                        .WithMany("PaymentsCollection")
                        .HasForeignKey("IdSubscription")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("APBD_Proj.Models.Companies", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("APBD_Proj.Models.Contracts", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("APBD_Proj.Models.Customers", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("APBD_Proj.Models.Discounts", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("APBD_Proj.Models.Software", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("APBD_Proj.Models.Subscriptions", b =>
                {
                    b.Navigation("PaymentsCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
